mode: "uq"

mechanism: "./FFCM-2/FFCM-2.yaml"

geometry:
  type: "impinging_jet"
  burner_diameter: 60.452e-03
  domain_width: 0.020

boundary_conditions:
  pressure: 101325.0
  burner_temperature:
    distribution: "uniform"
    min: 300
    max: 350
  stagnation_temperature:
    distribution: "normal"
    mean: 345.15
    stdev: 20
  composition: "C2H4:1.0, O2:3.0, N2:11.14, AR:0.14"
  fuel: "C2H4"
  flow_rates:
    C2H4:
      distribution: "normal"
      mean: 0.652
      stdev: 0.003
    O2:
      distribution: "normal"
      mean: 1.9635
      stdev: 0.0098
    N2:
      distribution: "normal"
      mean: 7.2930
      stdev: 0.0365
    AR:
      distribution: "normal"
      mean: 0.0935
      stdev: 0.0005

submodels:
  radiation: true
  transport: "multicomponent"
  soret: true

settings:
  meshing:
    grid_min_size: 1.0e-07
    max_grid_points: 1.0e+04
    ratio: 2
    slope: 0.015
    curve: 0.022
    prune: 0.0
  uq:
    epistemic_samples: 10
    aleatory_samples: 1
