datasets:
  - file_path: "./data/jet_Tb300_Ts345_15_Radiation_Multicomponent_Soret_phi1_0_FFCM2.csv"
    label: "FFCM-2"
    color: "k"
    linestyle: "-"
    marker: "None"
    markevery: 10

  - file_path: "./data/jet_Tb300_Ts345_15_Radiation_Multicomponent_Soret_phi1_0_GRI30.csv"
    label: "GRI 3.0"
    color: "gray"
    linestyle: "-"
    marker: "None"
    markevery: 10

plot_config:
  x_label: "Height above burner (mm)"
  x_lim: [-0.5, 20.5]
  y_label: "Temperature (K)"
  y_lim: [250, 1750]
  grid: true
  grid_color: "gray"
  grid_alpha: 0.25
  legend_loc: "lower center"
  legend_fontsize: 12
  output_file: "temperature.png"
